name: Build OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  FILE_NAME: CM520-79F

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      actions: write
      contents: write

    steps:
      - uses: actions/checkout@v5

      - name: Install Go 1.25.1
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'

      - name: Debug Go environment
        run: |
          echo "=== go info ==="
          go version
          go env GOPATH GOCACHE GOMODCACHE GOROOT

      - name: Clone OpenWrt source
        run: |
          git clone --depth=1 $REPO_URL -b $REPO_BRANCH openwrt
          cd openwrt
          echo "DATE=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "DATE1=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
          echo "useVersionInfo=$(git show -s --date=short --format='Author: %an<br/>date: %cd<br/>commit: %s<br/>commit hash: %H')" >> $GITHUB_ENV

      - name: Run diy-part1
        working-directory: openwrt
        run: |
          chmod +x $GITHUB_WORKSPACE/$DIY_P1_SH
          $GITHUB_WORKSPACE/$DIY_P1_SH

      - name: Update feeds
        working-directory: openwrt
        run: |
          set -euo pipefail
          ./scripts/feeds update -a >/dev/null
          ./scripts/feeds install -a >/dev/null
          echo "Checking OpenClash..."
          if [ ! -d "package/feeds/luci/luci-app-openclash" ] && [ ! -d "feeds/luci/applications/luci-app-openclash" ]; then
            echo -e "\033[31mERROR: luci-app-openclash not found\033[0m"
            exit 1
          fi

      - name: Run diy-part2
        working-directory: openwrt
        run: |
          chmod +x $GITHUB_WORKSPACE/$DIY_P2_SH
          [ -f "$GITHUB_WORKSPACE/$CONFIG_FILE" ] && cp -f "$GITHUB_WORKSPACE/$CONFIG_FILE" .config
          [ -d "$GITHUB_WORKSPACE/files" ] && cp -r "$GITHUB_WORKSPACE/files" ./files_overlay
          $GITHUB_WORKSPACE/$DIY_P2_SH

      - name: Ensure OpenWrt uses Go 1.25.1
        run: |
          mkdir -p openwrt/staging_dir/host/bin
          ln -sf $(which go) openwrt/staging_dir/host/bin/go
          echo "GOTOOLCHAIN=local" >> $GITHUB_ENV
          openwrt/staging_dir/host/bin/go version

      - name: Prepare build
        working-directory: openwrt
        run: |
          set -euo pipefail
          [ -f .config ] || make defconfig >/dev/null
          make download -j8 >/dev/null
          find dl -size -1024c -exec rm -f {} \; || true

      - name: Compile firmware (quiet by default)
        id: compile
        working-directory: openwrt
        run: |
          set -euo pipefail
          export PATH="$PWD/staging_dir/host/bin:$PATH"
          echo -e "\033[34mStarting quiet build... (only directory info)\033[0m"
          if ! make -j$(nproc); then
            echo -e "\033[33m⚠️ Build failed in quiet mode, retrying verbose...\033[0m"
            make -j1 V=s
          fi
          echo "status=success" >> $GITHUB_OUTPUT
          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME || true
          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
          echo "FILE_DATE=_$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Organize firmware
        if: steps.compile.outputs.status == 'success'
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages || true
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV

      - name: Upload firmware artifact
        if: steps.compile.outputs.status == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: ${{ env.FIRMWARE }}

      - name: Create GitHub Release
        if: steps.compile.outputs.status == 'success'
        uses: ncipollo/release-action@v1
        with:
          name: R${{ env.DATE }} for ${{ env.FILE_NAME }}
          allowUpdates: true
          removeArtifacts: true
          tag: ${{ env.FILE_NAME }}
          commit: main
          artifacts: ${{ env.FIRMWARE }}/*
          body: |
            - 默认IP：10.10.10.100 默认密码：无
            - 当前使用版本:【源码更新记录】
            ${{ env.useVersionInfo }}
