name: Build OpenWrt for CM520-79F

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  FILE_NAME: CM520-79F
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v5

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential g++ git wget curl ccache subversion unzip bzip2 gzip \
          python3 python3-venv python3-pip file rsync tar xz-utils patch gawk \
          bc flex bison gettext libncurses5-dev libssl-dev zlib1g-dev perl
        python3 -m pip install --upgrade pip setuptools wheel

    - name: Setup Go 1.25
      run: |
        mkdir -p $HOME/go1.25
        wget -q https://dl.google.com/go/go1.25.0.linux-amd64.tar.gz -O /tmp/go1.25.tar.gz
        tar -C $HOME/go1.25 -xzf /tmp/go1.25.tar.gz --strip-components=1
        rm /tmp/go1.25.tar.gz
        echo "$HOME/go1.25/bin" >> $GITHUB_PATH
        go version

    - name: Cache dl
      uses: actions/cache@v4
      with:
        path: openwrt/dl
        key: dl-${{ github.run_id }}
        restore-keys: dl-

    - name: Cache toolchain
      uses: actions/cache@v4
      with:
        path: openwrt/staging_dir
        key: toolchain-${{ github.sha }}
        restore-keys: toolchain-

    - name: Clone OpenWrt
      run: |
        git clone --depth=1 -b $REPO_BRANCH $REPO_URL openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Run diy-part1
      run: |
        [ -e $DIY_P1_SH ] && chmod +x $DIY_P1_SH && ./$DIY_P1_SH

    - name: Copy custom config
      run: |
        [ -e $CONFIG_FILE ] && cp $CONFIG_FILE openwrt/.config

    - name: Run diy-part2
      run: |
        cd openwrt
        [ -e ../$DIY_P2_SH ] && chmod +x ../$DIY_P2_SH && ../$DIY_P2_SH

    - name: Download packages
      run: |
        cd openwrt
        make download -j$(nproc)
        find dl -size -1024c -delete

    - name: Build OpenWrt
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 V=s
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
        echo "FIRMWARE=$(pwd)/bin/targets/*/*" >> $GITHUB_ENV

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Release firmware
      uses: ncipollo/release-action@v1
      with:
        name: R${{ env.FILE_DATE }} for ${{ env.FILE_NAME }}
        tag: ${{ env.FILE_NAME }}
        commit: main
        artifacts: ${{ env.FIRMWARE }}/*
        body: |
          - 默认IP：10.10.10.100 默认密码：无
          - Go 版本: 1.25
          - 编译时间: ${{ env.FILE_DATE }}
