# Build OpenWrt for CM520-79F
name: Build OpenWrt for CM520-79F

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  FILE_NAME: CM520-79F
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 150
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v5

    - name: Free up disk space
      run: |
        echo "Freeing up disk space..."
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        # Additional cleanup for more space
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /usr/local/graalvm
        sudo rm -rf /opt/microsoft
        df -h

    - name: Install build dependencies
      run: |
        echo "Enabling i386 architecture and installing dependencies..."
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses5-dev libssl-dev python3-dev python3-setuptools rsync unzip \
          zlib1g-dev file wget subversion patch upx-ucl autoconf automake \
          curl asciidoc binutils bzip2 gzip p7zip p7zip-full libelf-dev \
          lib32gcc-s1 libc6-dev lib32stdc++6 zlib1g-dev:i386 lib32z1-dev \
          ccache ecj fastjar re2c xz-utils python3 python3-pip python3-ply \
          python3-venv python3-yaml haveged lrzsz device-tree-compiler scons \
          antlr3 gperf intltool mkisofs qemu-utils swig tar
        echo "Cleaning apt cache..."
        sudo apt-get clean
        sudo apt-get autoremove -y

    - name: Setup Go (Version 1.25.0 )
      uses: actions/setup-go@v5
      with:
        # Pin to exact version 1.25.0 to satisfy the strict check in diy-part2.sh
        go-version: '1.25.0'

    - name: Setup ccache
      run: |
        echo "Setting up ccache for faster compilation..."
        sudo mkdir -p /usr/lib/ccache
        sudo ln -sf /usr/bin/ccache /usr/lib/ccache/gcc
        sudo ln -sf /usr/bin/ccache /usr/lib/ccache/g++
        sudo ln -sf /usr/bin/ccache /usr/lib/ccache/cc
        sudo ln -sf /usr/bin/ccache /usr/lib/ccache/c++
        export PATH="/usr/lib/ccache:$PATH"
        ccache --max-size=2G
        ccache --set-config=compression=true

    - name: Enhanced cache downloads
      uses: actions/cache@v4
      with:
        path: |
          openwrt/dl
          ~/.ccache
        key: dl-ccache-${{ env.REPO_BRANCH }}-${{ hashFiles('**/feeds.conf.default') }}-${{ github.run_number }}
        restore-keys: |
          dl-ccache-${{ env.REPO_BRANCH }}-${{ hashFiles('**/feeds.conf.default') }}-
          dl-ccache-${{ env.REPO_BRANCH }}-
          dl-ccache-

    - name: Enhanced cache toolchain
      uses: actions/cache@v4
      with:
        path: |
          openwrt/staging_dir
          openwrt/build_dir/toolchain-*
        key: toolchain-${{ env.REPO_BRANCH }}-${{ runner.arch }}-${{ hashFiles('**/.config') }}-v2
        restore-keys: |
          toolchain-${{ env.REPO_BRANCH }}-${{ runner.arch }}-
          toolchain-${{ env.REPO_BRANCH }}-

    - name: Clone ImmortalWrt source
      run: |
        git clone --depth=1 -b $REPO_BRANCH $REPO_URL openwrt
        cd openwrt
        echo "Current commit: $(git rev-parse HEAD)"
        echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Add additional feeds
      run: |
        cd openwrt
        echo "Adding golang and node feeds..."
        echo "src-git golang https://github.com/sbwml/packages_lang_golang;22.x" >> feeds.conf.default
        echo "src-git node https://github.com/nxhack/openwrt-node-packages.git" >> feeds.conf.default
        echo "Updated feeds configuration:"
        cat feeds.conf.default

    - name: Update and install feeds
      run: |
        cd openwrt
        echo "Updating feeds..."
        ./scripts/feeds update -a
        echo "Installing feeds..."
        ./scripts/feeds install -a

    - name: Run DIY part1 script
      run: |
        cd openwrt
        if [ -f "../$DIY_P1_SH" ]; then
          echo "Running $DIY_P1_SH..."
          chmod +x "../$DIY_P1_SH"
          "../$DIY_P1_SH"
          echo "DIY part1 script completed"
        else
          echo "DIY part1 script not found, skipping"
        fi

    - name: Copy custom configuration
      run: |
        cd openwrt
        if [ -f "../$CONFIG_FILE" ]; then
          cp "../$CONFIG_FILE" .config
          echo "Custom .config copied"
        else
          echo "Custom .config not found, using default"
          make defconfig
        fi

    - name: Run DIY part2 script
      run: |
        cd openwrt
        if [ -f "../$DIY_P2_SH" ]; then
          echo "Running $DIY_P2_SH..."
          chmod +x "../$DIY_P2_SH"
          "../$DIY_P2_SH"
          echo "DIY part2 script completed"
        else
          echo "DIY part2 script not found, skipping"
        fi

    - name: Generate final config
      run: |
        cd openwrt
        make defconfig
        echo "Configuration synchronized"

    - name: Download packages with retry
      run: |
        cd openwrt
        echo "Downloading packages..."
        # First attempt with parallel download
        if ! timeout 1800 make download -j$(nproc) V=s; then
          echo "Parallel download failed or timed out, cleaning and retrying..."
          find dl -size -1024c -delete 2>/dev/null || true
          if ! timeout 1800 make download -j1 V=s; then
            echo "Single thread download failed, trying one more time..."
            find dl -size -1024c -delete 2>/dev/null || true
            timeout 1800 make download -j1 V=s || {
              echo "Download completely failed, but continuing with available packages..."
            }
          fi
        fi
        find dl -size -1024c -delete 2>/dev/null || true
        find dl -name "*.hash" -delete 2>/dev/null || true
        echo "Download completed. Cache size:"
        du -sh dl/ || true

    - name: Monitor system resources
      run: |
        echo "=== System Resources Before Build ==="
        echo "CPU cores: $(nproc)"
        echo "Memory info:"
        free -h
        echo "Disk space:"
        df -h
        echo "Load average: $(cat /proc/loadavg)"

    - name: Compile toolchain with monitoring
      run: |
        cd openwrt
        export PATH="/usr/lib/ccache:$PATH"
        echo "Compiling toolchain..."
        echo "Using ccache: $(which gcc)"
        
        if ! timeout 3600 make tools/install -j$(($(nproc)+1)) V=s; then
          echo "Tools compilation failed or timed out, retrying with single thread..."
          if ! timeout 3600 make tools/install -j1 V=s; then
            echo "Tools compilation failed completely"
            exit 1
          fi
        fi
        
        if ! timeout 3600 make toolchain/install -j$(($(nproc)+1)) V=s; then
          echo "Toolchain compilation failed or timed out, retrying with single thread..."
          if ! timeout 3600 make toolchain/install -j1 V=s; then
            echo "Toolchain compilation failed completely"
            exit 1
          fi
        fi
        
        echo "Ccache statistics:"
        ccache -s || true

    - name: Build OpenWrt firmware with enhanced monitoring
      run: |
        cd openwrt
        export PATH="/usr/lib/ccache:$PATH"
        echo "Starting firmware build..."
        echo "Available CPU cores: $(nproc)"
        echo "Available memory:"
        free -h
        
        # Monitor resources during build
        (
          while true; do
            sleep 300  # Check every 5 minutes
            echo "=== Build Progress Check $(date) ==="
            echo "Memory usage:"
            free -h
            echo "Disk usage:"
            df -h . || true
            echo "Load average: $(cat /proc/loadavg)"
            echo "Ccache stats:"
            ccache -s || true
            echo "================================"
          done
        ) &
        MONITOR_PID=$!
        
        # Main build with timeout
        BUILD_SUCCESS=false
        if timeout 7200 make -j$(($(nproc)+1)) V=s; then
          BUILD_SUCCESS=true
        else
          echo "Parallel build failed or timed out, retrying with fewer threads..."
          if timeout 3600 make -j2 V=s; then
            BUILD_SUCCESS=true
          else
            echo "Reduced parallel build failed, trying single thread..."
            if timeout 3600 make -j1 V=s; then
              BUILD_SUCCESS=true
            fi
          fi
        fi
        
        # Stop monitoring
        kill $MONITOR_PID 2>/dev/null || true
        
        if [ "$BUILD_SUCCESS" = "true" ]; then
          echo "Build completed successfully!"
          echo "Final ccache statistics:"
          ccache -s || true
        else
          echo "Build failed after all retry attempts"
          echo "Final system state:"
          free -h
          df -h
          exit 1
        fi

    - name: Prepare outputs
      run: |
        cd openwrt
        DEVICE_NAME=$(grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' | head -1)
        if [ -z "$DEVICE_NAME" ]; then
          DEVICE_NAME="unknown"
        fi
        echo "DEVICE_NAME=$DEVICE_NAME" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
        echo "FIRMWARE_PATH=$(pwd)/bin/targets/*/*" >> $GITHUB_ENV
        echo "Firmware files:"
        ls -la bin/targets/*/* || true

    - name: Check firmware size
      run: |
        cd openwrt
        echo "Firmware size information:"
        find bin/targets -name "*.bin" -o -name "*.img" -o -name "*.trx" 2>/dev/null | while read file; do
          if [ -f "$file" ]; then
            size=$(stat -c%s "$file" 2>/dev/null || echo "0")
            echo "$(basename "$file"): ${size} bytes ($(numfmt --to=iec $size 2>/dev/null || echo "unknown"))"
          fi
        done || echo "No firmware files found"

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_${{ env.FILE_NAME }}_${{ env.DEVICE_NAME }}_${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE_PATH }}
        retention-days: 30

    - name: Upload build logs and config
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-info_${{ env.FILE_DATE }}
        path: |
          openwrt/logs/
          openwrt/.config
          openwrt/bin/packages/
        retention-days: 7

    - name: Create GitHub Release
      if: success()
      uses: ncipollo/release-action@v1
      with:
        name: OpenWrt ${{ env.FILE_NAME }} - ${{ env.FILE_DATE }}
        tag: ${{ env.FILE_NAME }}-${{ env.FILE_DATE }}
        commit: ${{ github.sha }}
        allowUpdates: true
        artifacts: ${{ env.FIRMWARE_PATH }}/*
        body: |
          ## OpenWrt Firmware for ${{ env.FILE_NAME }}
          
          **Device**: ${{ env.DEVICE_NAME }}  
          **Build Date**: ${{ env.FILE_DATE }}  
          **Source**: ImmortalWrt ${{ env.REPO_BRANCH }}  
          **Commit**: ${{ env.COMMIT_HASH }}  
          **Go Version**: 1.25.0
          
          ### Default Settings
          - **Default IP**: 10.10.10.100
          - **Default Password**: (none)
          - **Web Interface**: http://10.10.10.100
          
          ### Installation
          1. Flash the appropriate firmware file for your device
          2. Wait for the device to boot completely
          3. Connect via web browser to configure
